### ISSUE TITLE
Android: Menus are too dark in dark theme

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1145]
![screenshot_20181104-220144](https://user-images.githubusercontent.com/44229/47978956-7bb16000-e08e-11e8-89c4-6553e9157aab.png)

From a user email: "Please fix Dark and Black Themes so the menus are readible (see attached photo)."

**Comment by dosiecki** [comment]
I'm reasonably certain this is simply due to the fact that our themes are built on the light/dark platform default themes, and some ROMs have popped up that have defaults different than the stock ones.  We should be able to simply copy some of the default/stock rules into our overrides.

**Comment by tjkirch** [comment]
I have this on stock (Android One) with nothing going on theme-wise at the system level, so I'm not sure it's due to the ROM?

**Comment by caleb-allen** [comment]
@tjkirch are you still seeing this issue?

What device are you using?

**Comment by tjkirch** [comment]
@caleb-allen 

> @tjkirch are you still seeing this issue?

Yep, still have nearly unreadable menus.  There hasn't been a NewsBlur Android update since July 19, 2018, so I'm not sure what would cause a change.

> What device are you using?

I'm using a Moto X4 with Android 9.  No root, nothing special.  Newsblur is in "Dark" theme.  (It's the same in the "Black" theme.)

**Comment by caleb-allen** [comment]
I think @dosiecki is correct, that Motorola may have some subtle issues with their default holo theming.

If the main app theme is still respected on those manufacture ROMs, this should fix the issue, overriding the faulty default text color.

**Comment by tjkirch** [comment]
Does that mean that the next NewsBlur Android release will have more explicit styling to work around manufacturers' system-level styles? (Just hoping to understand)

**Comment by tjkirch** [comment]
Ah, now I see the related pull request, sorry - the client I'm using didn't show the connection.

**Comment by manderson23** [comment]
I'm still seeing this on a Moto G6 running Android 9 (PPS29.55-24) with v9.0.1.

**Comment by caleb-allen** [comment]
@tjkirch did this fix your issue?

If not I'll need to get my hands on a Moto device, the app theme is being overridden somehow.

**Comment by tjkirch** [comment]
@caleb-allen Unfortunately not - I just confirmed the dark menu on v9.0.1.

**Comment by caleb-allen** [comment]
> I just confirmed the dark menu on v9.0.1.

Thanks for confirming. It seems that it's unique to Moto. I'm gonna need to get my hands on a device to test, or else a virtual Moto device.

**Comment by manderson23** [comment]
I'll try to investigate further on my Moto device and see if I can fix it.
