### ISSUE TITLE
iOS Catalyst: small tweaks

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1451]
Three small issues:

1) the Done button takes the user back to the story list, not the feed list, on iPhone 

2) the green dot shows up on initial load.
![29C84374-5A69-42BF-B64D-37DAD16D0AC4](https://user-images.githubusercontent.com/44229/114715393-06d3bd00-9d01-11eb-94a2-96df58d07ace.png)

3) the white line on the bottom of the loader
![F3A160B7-52F1-4D8B-9B12-7CD2E44738AE](https://user-images.githubusercontent.com/44229/114715418-0cc99e00-9d01-11eb-9a8a-ab3ff7ad8397.png)

**Comment by Dejal** [comment]
I've fixed the first two, but couldn't reproduce the last one. I made a change that might fix it anyway. If not, feel free to re-open, along with steps to repro.

**Comment by samuelclay** [comment]
Yeah it's still there. It's on the light grey theme and only on the first story loading cell. Use Global Shared Stories or something slow to trigger it.

**Comment by samuelclay** [comment]
Version 11.0 just went out on TestFlight. Here's the release notes:

Version 11.0 is a big one! 
- All new three column layout for iPad
- New full screen layout for iPhone
- Updated styling to match beta.newsblur.com
- The word "the" is now ignored when ordering the site list
- Updated keyboard shortcuts
- Pull to Insta-fetch stories
- Added support for Edge and Brave browsers
- A healthy number of small issues were fixed

Anything to add?

**Comment by nriley** [comment]
Perhaps worth documenting #1422 is a known issue as it still isn't fixed.

**Comment by samuelclay** [comment]
Hah, I'm struggling with #1422 on the web as well. Full bleed images are hard due to lots of offsetting html. Different reasons I realize, but I wish they were easier to blow up. We're already letting them snap from padding to full bleed. 

I do the opposite on the web (on beta.newsblur.com only) and do full-bleed by default and shrink smaller images after a short delay. It remains to be seen which is a better experience.

**Comment by Dejal** [comment]
Yay for TestFlight. There may be other changes, but nothing is springing to mind. I'll be available today and tomorrow for any urgent fixes that are needed, and can juggle beyond that if needed.

**Comment by nriley** [comment]
We're getting a bit off topic, but I wonder if there's any newer CSS tricks we can use that do not involve hard-coding pixel widths… I am far from up on modern CSS.

**Comment by Dejal** [comment]
Back on topic, I don't see the line on the loading row. I can't think of any settings that could affect it, can you?

![Blinky](https://user-images.githubusercontent.com/1318849/115939336-ace69c00-a452-11eb-891e-ecd775e70817.gif)

**Comment by samuelclay** [comment]
Found it, change your iOS System appearance to Light. In iOS-wide dark mode, it's correct.

**Comment by Dejal** [comment]
I can reproduce this now, but I can't figure out how to prevent it happening. Setting the separator color, changing the separator style to none, changing the margins, and several other things I tried didn't have any effect. The only other thing I can think of is to delve into the internal view structure (the separator is a private subview) and try to change it by brute force, but that may break in future iOS versions, and tempt the App Review hammer, so I wouldn't advise it.

So, I'll just close this.
