### ISSUE TITLE
Web: 'v'/'o' no longer open stories in background

### ISSUE THREAD

**Issue by TheQwerty** [samuelclay/NewsBlur#655]
Chrome 41.0.2272.16 beta (64-bit)
OS X Mavericks 10.9.5

Preference Stories > Open Links > In New Tab is selected.
Using 'Feed' view and 'Full' mode (not 'List').

Focusing a story via 'j'/'k' and then pressing 'o' opens the story in a foreground tab.
The expected behavior is for it to open in a background tab.

I'm assuming Chrome just updated because it was definitely working last weekend and other than possibly Newsblur that's the only thing that could be different.

I'm not seeing any errors or warnings in the Console, so I'm guessing Google changed the handling of `MouseEvents`. In looking at the `open_story_in_new_tab` function within _NewsBlur/media/js/newsblur/models/stories.js_ I notice it uses `init_mouse_events` which [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent.initMouseEvent) says is deprecated. I'm not well versed in JS and my attempt at changing that (and the previous line) to `b = new MouseEvent("click", {bubbles: true, cancelable: true, view: window, ctrl:true, meta:true});` in Chrome's dev tools only made it open the link in the current tab instead.

This was also noted by another user on [GetSatisfaction](https://getsatisfaction.com/newsblur/topics/open_articles_in_a_new_tab?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Breply_id%5D=15040085#reply_15040085).

**Comment by samuelclay** [comment]
Another thread here: https://getsatisfaction.com/newsblur/topics/the-o-key-opens-new-foreground-tab-in-latest-chrome-and-firefox

Looks like Chrome needs to be fixed, since NewsBlur is explicitly opening in the background.

**Comment by TheQwerty** [comment]
It's a bit disingenuous to say "Newsblur is explicitly opening in the background". Newsblur is simulating click events and relying on Ctrl+Meta+Click to open in the background. Unfortunately, that appears to be the "standard" way of achieving this lacking true support from Javascript & the browsers, so indeed it's not a Newsblur specific problem. (The Vimium extension [suffers](https://github.com/philc/vimium/issues/1279) from this too.)

It seems the proper way to achieve this would be for Newsblur to have a browse extension which handles the opening in a background tab. There are proper APIs for extensions to create tabs in both [Chrome](https://developer.chrome.com/extensions/tabs#method-create) and [Firefox](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/tabs)


There's been a few issues on the Chromium tracker that seem to cover this issue but currently this one seems to have the most promise if any developers want to chime in or track: https://code.google.com/p/chromium/issues/detail?id=454222

**Comment by samuelclay** [comment]
I'm not so sure that it's disingenuous to say that NewsBlur explicitly opens links in the background. Take a look at this code:

```
    open_story_in_new_tab: function(background) {
        this.mark_read({skip_delay: true});

        if (background && !$.browser.mozilla) {
            var anchor, event;

            anchor = document.createElement("a");
            anchor.href = this.get('story_permalink');
            event = document.createEvent("MouseEvents");
            event.initMouseEvent("click", true, true, window, 0, 0, 0, 0, 0, true, false, false, true, 0, null);
            return anchor.dispatchEvent(event);
        } else {
            window.open(this.get('story_permalink'), '_blank');
            window.focus();
        }
    },
```

Looks pretty explicit to me. I'm working with what I've got. Making a browser extension, which I'm no stranger to (see github.com/samuelclay/hackersmacker), is not the right answer. The browser should support optional new background tabs.

**Comment by TheQwerty** [comment]
It explicitly says Ctrl+Meta+Click a link.
It implicitly expects that the browser treat Ctrl+Meta+Click as open link in background tab.

It seems this simulated click method is the standard way of achieving this, but it is also a bit of a hack. It's unfortunate that Javascript's `window.open` is still stuck in a pre-tab time and that there is apparently no official way for websites to open background tabs with the user's permission except through the browser extension APIs. (Which I'd argue is the right answer if it becomes the only answer.)

> The browser should support optional new background tabs.

 I entirely agree, so I hope there will be more support for the Chromium issue I linked above. They've currently marked it as moved to v42, so things are likely to get noisy when v41 hits stable.

**Comment by benubois** [comment]
It [sounds like](https://code.google.com/p/chromium/issues/detail?id=456910) it is Chromium's intention to only allow background tab creation via extensions unfortunately.

**Comment by nriley** [comment]
Unfortunately this affects Safari as of Safari 10; it opens the link in the current tab instead. Unclear if this is an intentional change. Constructing a mouse event still works in current (beta, even) versions of Chrome.  I tried the newer event creation API too (which is a bit easier to read).

`var b = new MouseEvent('click', {ctrlKey: true, metaKey: true, view: window}); var a = document.createElement("a"); a.href = 'https://google.com/'; a.dispatchEvent(b);`

**Comment by nriley** [comment]
This wasn't fixed in the final version of Safari 10.  I have made some progress towards a browser extension-based solution.  Here's a very simple Safari extension that opens all link clicks in a background tab:

https://github.com/nriley/OpenInBackgroundTab

However, this *doesn't* trigger with the fake click event as constructed by `open_story_in_new_tab`.  It seems you used to be able to successfully write to element prototypes in Safari extensions, but you can't do that any more.  However, if you trigger a click event on an element attached to the DOM, e.g.:

```
var event = document.createEvent("MouseEvents"); event.initMouseEvent("click", true, true, window, 0, 0, 0, 0, 0, true, false, false, true, 0, null); document.getElementsByTagName('a')[0].dispatchEvent(event);
```

my extension does trigger.  This shouldn't be a big deal in changing what NewsBlur does.  However I've already spent way longer than I intended on it this morning…

**Comment by nriley** [comment]
OK, realized I was *so* close I made a change to register a custom event rather than overriding the `click` event.  Now, if you execute this in the context of a NewsBlur session:

```
NEWSBLUR.Models.Story.prototype.open_story_in_new_tab = function (background) {
    var event = new CustomEvent("openInNewTab", {
        bubbles: true,
        detail: {background: background}
    });
    $('a.NB-feed-story-title')[0].dispatchEvent(event);
}
```

it'll start opening pages in the background again.  The tab positioning still could use some work though.

**Comment by samuelclay** [comment]
Can you add a global variable (something like NEWSBLUR.safari_extension_version) that I can look for an then use in stories.js?

**Comment by nriley** [comment]
Sadly no, I can't write to NEWSBLUR or anything else outside the DOM, but I have changed it to return false from dispatchEvent, so you can tell if it actually did anything.  (It'll also return true if the handler fails for any reason, such as a missing 'detail' parameter).

I've provided a signed version so you can install it by double-clicking and renamed the repo, since it also supports foreground tabs now:

https://github.com/nriley/OpenInNewTab

**Comment by samuelclay** [comment]
Can you update the extension to only work on *.newsblur.com?

**Comment by samuelclay** [comment]
Ok, I got it to work by adding some code to `open_story_in_new_tab` but I'm not getting anything returned from `dispatchEvent` to signal that the extension is installed.

```
open_story_in_new_tab: function(background) {
    this.mark_read({skip_delay: true});

    // Safari browser on Linux is an impossibility, and thus we're actually
    // on a WebKit-based browser (WebKitGTK or QTWebKit). These can't handle
    // background tabs. Work around it by disabling backgrounding if we
    // think we're on Safari and we're also on X11 or Linux
    if ($.browser.safari && /(\(X11|Linux)/.test(navigator.userAgent)) {
        background = false;
    }
    
    if (background && $.browser.webkit) {
        var event = new CustomEvent("openInNewTab", {
            bubbles: true,
            detail: {background: background}
        });
        var success = this.story_title_view.$st.find('a')[0].dispatchEvent(event);
        if (success) {
            console.log(['Used safari extension to open link in background', success]);
            return;
        } else {
            console.log(['Safari extension failed to open link in background', success, this.story_title_view.$st.find('a')[0]]);
            return;
        }
    }
    
    if (background && !$.browser.mozilla) {
        var anchor, event;

        anchor = document.createElement("a");
        anchor.href = this.get('story_permalink');
        event = document.createEvent("MouseEvents");
        event.initMouseEvent("click", true, true, window, 0, 0, 0, 0, 0, true, false, false, true, 0, null);
        return anchor.dispatchEvent(event);
    } else {
        window.open(this.get('story_permalink'), '_blank');
        window.focus();
    }
},
```

**Comment by nriley** [comment]
I've updated the extension to only work on *.newsblur.com.

You've got the test backwards — it'll return *false* if it works, and true if it doesn't (or isn't installed).  I tried returning other things (like version numbers :) but it just turned into 'true'.

**Comment by nriley** [comment]
I haven't been able to get updates to work in the old ad-hoc method so I think I/we may need to submit this extension to the Safari Extensions gallery. Do you want to make it an official NewsBlur thing or should it just be a project I support?  I don't care one way or the other (but cannot make any promises about timeliness of updates).

**Comment by samuelclay** [comment]
We've got a precedent on other browser extensions being run by their maintainers, so go ahead and submit to the Safari Extension Gallery. It doesn't look like anything else had to be done to the other extensions after getting it to work. And I can handle some things on my side if they do come up.

I'll add this to Goodies once approved. I've also deployed the changes.

**Comment by samuelclay** [comment]
I'll close as soon as the extension is live.

**Comment by nriley** [comment]
I have submitted the extension to the gallery. If all else fails, we can see about bundling it in an app, although this will only work on more recent OS versions.

**Comment by samuelclay** [comment]
Sweet, thanks!

**Comment by moiselacy** [comment]
I've installed the safari extension (v1.05) and am using Safari 10.0 (12602.1.50.0.10) on MacOS Sierra, but using the o/v shortcuts still doesn't open links in the background. I miss being able to just go through a feed and open links in new background tabs. 

With the extension installed and when Newsblur is a pinned tab, it opens the link in a new tab in the foreground. I tried unpinning the tab and it just opens the link in the same tab.

Am I missing something? Do I need to do anything else besides install the extension? Thanks!

**Comment by samuelclay** [comment]
Did you reopen the tab? I found that it only works on reload.

**Comment by nriley** [comment]
@moiselacy — how do you have Preferences > Tabs configured? Any other extensions installed? I can't think of too much that could go wrong, assuming you have actually reloaded the pinned tab...

**Comment by moiselacy** [comment]
Thanks for the quick replies. I've unpinned the Newsblur tab, closed it, restarted safari, opened Newsblur again. Same behavior. 

![Preferences>Tabs](https://cloud.githubusercontent.com/assets/22669945/19177036/8e739090-8c13-11e6-8dcb-588a78593996.png)
![Installed Extensions](https://cloud.githubusercontent.com/assets/22669945/19177039/95a403d6-8c13-11e6-8793-b303581f2314.png)

**Comment by nriley** [comment]
One more thing I forgot to ask, since you're asking on GitHub — are you using newsblur.com or your own installation?  The extension is currently limited to working on newsblur.com, though it'd be simple to change that (and I probably should...)

If you are using newsblur.com, can you try unchecking your other extensions, restarting Safari and making sure it's not a conflict? (The only one I use as well as 1Password, which I'm pretty sure does  not conflict.)

**Comment by moiselacy** [comment]
I'm using the main newsblur.com site. I just unchecked all of my other extensions, restarted Safari, opened newsblur.com, and still seeing the same behavior. Could it be specific to any of my Newsblur preferences?

**Comment by samuelclay** [comment]
It shouldn't have anything to do with preferences. I can get it to work on my machine, so I'm wondering if you have any other browser extensions that may be conflicting. Can you turn off all of the other extensions, reload newsblur, and then check? Do you see any errors in the error console? Can you check the error console?

**Comment by moiselacy** [comment]
I've unchecked all of my browser extensions (except this one), closed newsblur.com, restarted Safari, then opened newsblur.com, but I'm still seeing the same behavior. 

Looking at the error console when i hit 'o' in an active story, I see this error as it loads the story in the same tab: WebSocket connection to 'ws://newsblur.com/socket.io/1/websocket/wX3DYcrtzv4XggXUvyiV' failed: WebSocket is closed due to suspension.

**Comment by moiselacy** [comment]
Ah ha! Ok, I know why it wasn't working. I was loading http://newsblur.com, not www.newsblur.com. 

The extension checked to see if I was coming from ".newsblur.com":
` if (!e.srcElement.ownerDocument.domain.toLowerCase().endsWith('.newsblur.com'))`
        `return;`

Order has been restored in my Newsblur reading habits! Thanks to both of your for taking the time to help me troubleshoot this.

**Comment by samuelclay** [comment]
Yep, that'll do it. Glad that got worked out.

**Comment by nriley** [comment]
Wow.  Will fix that!  Thanks.

**Comment by nriley** [comment]
OK, fixed in 1.1.  Same download URL.  This also adds the ability to specify a custom NewsBlur domain.

![custom domain](https://cloud.githubusercontent.com/assets/68303/19294657/93f5ceb0-8ffc-11e6-8bcf-428a3bcff7ed.png)

**Comment by samuelclay** [comment]
Is this in the Safari Gallery yet? I'd love to blog it.

**Comment by nriley** [comment]
It's now been a week.  The message you get when you submit reads "We will review your extension and email you soon".  I don't know what "soon" is, but from what I can read it may be 2-3 weeks.  I just submitted 1.1 today.  I updated the Web page (https://github.com/nriley/OpenInNewTab) with a README so you can link to it, if you want to go that way instead.

**Comment by samuelclay** [comment]
Looks like opening in a new tab in safari has broken. I've had to disable this code in order to make it work. Happy to integrate a solution for this extension to get it working again. Here's the code I removed: b3337acee

**Comment by nriley** [comment]
The extension still works — I use it every day on current macOS. Code is here: https://github.com/nriley/NewsBlur-Helper.

I got busy with other things (many life changes…) and never did an official release of this. However I think it is very close. Because this is a Safari app extension and not a web extension I believe it can be signed/notarized and does not need to be distributed through the App Store.

Without the extension present it has always opened links in the current tab; don't think this is anything new.

**Comment by nriley** [comment]
Thanks!
