### ISSUE TITLE
iOS: Sharing extension

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#755]
Share stories from other iOS apps. Everything's built on the backend, just need to develop the UI.

**Comment by acdha** [comment]
:+1:

I use the iOS sharing extensions from all sorts of other apps and this would be a nice time-saver, particularly on a slow old phone

**Comment by adamcstephens** [comment]
This is my number one feature request on iOS, and if not implemented will bring me to reconsider staying premium. Please!

**Comment by samuelclay** [comment]
I've attempted to build it under branch shareext, it proved to be too difficult for one day. I'll get back to it, but it's not a trivial addition.

**Comment by Dejal** [comment]
I'd like to have a go at this soon.  Is it ready for me, or does anything need changing on the backend first?

**Comment by samuelclay** [comment]
This is ready. Use the same endpoint as the bookmarklet.

**Comment by samuelclay** [comment]
By the way, are we ready for a wide release? This is version 5.0 after all, and I'd like to submit it to the app store soon. I haven't heard any more feedback apart from the rotation issues, which are fixed now.

**Comment by Dejal** [comment]
Need to add the extra fonts (or at least remove the demo one), but other than that I think it's in good shape for a release.  The remaining issues could go in the next version.  Though I'm working on the iPad Pro issue at present, so you might want to wait for that.

**Comment by Dejal** [comment]
It looks like the 'share_token' property is not published by the production server (it's in apps/reader/views.py in the shareext branch: `'share_token': user.profile.secret_token`).  I don't have a local server, so can you add this to the production server?

**Comment by Dejal** [comment]
You said above to use the bookmarklet URL (`https://www.newsblur.com/api/add_site_load_script/?url=[url]&time=[time]`), but presumably that wouldn't work if the user isn't logged in?  I notice the bookmarklet URL includes an identifier-like value at the end of the path if logged into the website.  Is that available in the iOS app, or is that the aforementioned share token?

**Comment by samuelclay** [comment]
Save this for v5.1. Let's get the 3d touch action #806 done first, as well as any remaining bugs.

**Comment by samuelclay** [comment]
Added `share_ext_token` to /reader/feeds?flat=true.

**Comment by Dejal** [comment]
I was just looking at this again.  I notice that you used the action extension template instead of the share extension one.  Is there a reason for that?  The action extension is for manipulating data, e.g. transforming text or marking up an image.  I think NewsBlur should use a share extension instead, which are designed to share with websites & services.  (They both appear in share sheets; action extensions appear on the bottom with grayscale icons, share extensions appear on the top with color icons.)

**Comment by samuelclay** [comment]
Nice catch. The reason is because I had not yet made the distinction. I agree with using a share extension, that's where this belongs. One day when I extend the bookmarklet to allow you to save a story instead of sharing it, we can add that to an action extension, since the theme to me looks like share extensions are for sending content out to the internet and action extensions are for retaining data.

**Comment by Dejal** [comment]
I've just replaced the action extension with a sharing extension.  The UI works correctly now.

It uses the bookmarklet URL, as requested.  But I think we need a dedicated endpoint, since the bookmarklet displays a view in the browser to get comments, which seems to prevent the share extension's URL request from working.  We just need an endpoint to take the token, url and comments and do the appropriate thing without any further interaction.  Or at least modify it to bypass the comment view if there's a comments parameter.

**Comment by samuelclay** [comment]
What URL isn't working and why is it not being allowed?

**Comment by Dejal** [comment]
The URL is built thusly:

    NSURL *url = [NSURL URLWithString:[NSString stringWithFormat:
        @"https://%@/api/add_site_load_script/%@/?url=%@&time=%@&comments=%@", 
        host, token, encodedURL, @(time), encodedComments]];

e.g. https://www.newsblur.com/api/add_site_load_script/[TOKEN]/?url=https://www.apple.com/ipad-pro/&time=1450637181&comments=iPad%C2%A0Pro%20-%20Apple

(with my token masked, just in case.)

This is the bookmarklet URL (but with a `comments` parameter added).  As you know, the bookmarklet would show a view in the browser to get the comments, which would interfere with use from the share extension.

**Comment by samuelclay** [comment]
I'm a bit confused. We don't need to display the comments from the post. The share extension is just to get comments and shares into newsblur. It's not necessary to replicate the bookmarklet experience. The share extension should just pop up the ShareStoryViewController.

**Comment by Dejal** [comment]
Yes, I know.  The problem is that that URL doesn't save the shared URL and comments to NewsBlur.  It wants to interact with the user.  We need either a different endpoint URL to directly share the provided values, or modify this one to directly share instead of trying to interact.  Make sense?

**Comment by Dejal** [comment]
Put another way: when you click on the "Share on NewsBlur" bookmarklet in a browser window, you get a Javascript-generated view and need to click "SHARE THIS STORY" before it is actually shared to the NewsBlur site:

![screen shot 2015-12-20 at 11 04 26](https://cloud.githubusercontent.com/assets/1318849/11919495/79916c50-a709-11e5-8d4f-1d2200a628ac.png)

For the iOS sharing extension, this extra step interferes.  The sharing extension needs a URL it can send the info to share (URL and optional comments, along with the token) in one step.

**Comment by samuelclay** [comment]
Ah-ha, I'll build that in later today. The URL you're looking for is inside that add_site_load_script endpoint. I'll have to draw up another endpoint that is authenticated, since the iOS app has the auth cookies.

**Comment by samuelclay** [comment]
Ok, it's in. Just hit /api/share_story/ without a token. It should work for an authenticated user. This is untested on the authenticated side, though it should work just fine.

**Comment by Dejal** [comment]
I've made that change, and the request appears to succeed without error, but the story doesn't appear on the NewsBlur site -- it should be in my Blurblog, should it not?

I tried both without and with the token; no difference.

Are there any other required POST values, other than `story_url`?  (I also include `comments`.)

I did notice that the authentication challenge delegate method was called if implemented.  Could be a clue.

Are you able to search the server logs for the request?  I did it with my Dejal account, submitting the http://www.apple.com/ipad/ URL.  There should be several of those, the most recent around 21:30 PST.

**Comment by samuelclay** [comment]
Go to the newsblur .pch file in the project and turn on PROD_DEBUG. That switches the servers over to debug.newsblur.com, where I can easily see what's going on. Try that and I'll let you know what it looks like.

**Comment by Dejal** [comment]
Okay, I've just done that, and shared the same url.

**Comment by samuelclay** [comment]
Looks like it's am missing a `title` param. I'm sorry that it didn't spit that out in the error message. I'm fixing that right now. It should have as it does elsewhere, but this is a rather old section of the code that doesn't really get much love.

**Comment by samuelclay** [comment]
I've deployed a fix to debug and production. You should now see the error. 'story_url', 'comments', 'title', and 'content' and required params.

**Comment by Dejal** [comment]
I've modified it to include a `title` parameter, and pass a blank string for `comments` if the comments are the same as the title (as the share extension uses the page title as the default comment).

But what is the `content` parameter?  What value should be passed?  Is it like a content encoding?

I'm not seeing any error, though.

**Comment by samuelclay** [comment]
Content is the story itself. If you pass an empty string, the backend will fetch the url and run the Text view on it. If you're given content, use that. It all depends on what the host app is giving, right?

**Comment by Dejal** [comment]
Ah, gotcha.  It now includes all of those parameters, as appropriate.  I'm still not seeing anything show up on the NewsBlur site (maybe due to using PROD_DEBUG?).  How's things look from your side?

**Comment by samuelclay** [comment]
PROD_DEBUG is still production servers, so anything you do on debug is for real. I just have full logging turned on in debug, which lets me see POST/GET params, sql/mongo/redis queries, timing, and exceiptions.

In this case, it looks like I bungled the code as it had an error. Try again now. I just fixed it up quite a bit.

**Comment by samuelclay** [comment]
Were you getting 500 errors before? You should have been. Now you should see proper messages and error codes.

**Comment by Dejal** [comment]
Tried again, with both a URL and text.  No errors, but still not seeing anything in my Blurblog.

**Comment by samuelclay** [comment]
Doesn't look like you're authenticated.

127.0.0.1 - - [23/Dec/2015:18:24:30 +0000] "POST /api/share_story HTTP/1.1" 200 - "-" "Share%20Extension/1 CFNetwork/758.2.8 Darwin/15.2.0"

[Dec 23 18:24:30] {u'content': u'', u'story_url': u'http://www.apple.com/ipad/', u'comments': u'iPad - Apple', u'title': u''}
[Dec 23 18:24:30] [1] 0.291s: SELECT * FROM "profile_profile" WHERE "profile_profile"."secret_token" IS NULL
[Dec 23 18:26:16] {u'content': u'Just a test', u'story_url': u'', u'comments': u'', u'title': u''}
[Dec 23 18:26:16] [1] 0.321s: SELECT * FROM "profile_profile" WHERE "profile_profile"."secret_token" IS NULL

Only reason it's checking for a token is that the authentication cookie isn't being passed. I bet the share extension doesn't share the NSUrlSession (or whatever it's called) data, which means cookies aren't being automatically used.

In this case, store the 'secret_token' parameter you get back from /reader/feeds in NSUserDefaults and then use that token here.

**Comment by Dejal** [comment]
Success!

Yeah, I had commented out the token, since you said it wouldn't be needed, but I agree that the cookie likely isn't shared.  But sending the token worked successfully.  Excellent.

One remaining issue is that the share sheet defaults the page title as the comment, and I don't think I can get the title without loading the page.  So I always send a blank title.  I suggest that you modify the server side to get the page title when you load the URL, and omit the comment if it's the same (i.e. the user didn't replace the default comment with something else).

**Comment by samuelclay** [comment]
Editing comments is handled already, but I'll add title fetching as well. Thanks!

**Comment by samuelclay** [comment]
Deployed title fetching.

**Comment by Dejal** [comment]
The title isn't appearing.  Should support fetching the title when there is a `story_url` and blank `title` (as there always will be when sharing URLs from Safari etc).

**Comment by samuelclay** [comment]
Hmm, I'm not sure why not. I just tested on my local machine and it grabbed the title. What URL are you using?

**Comment by Dejal** [comment]
I think I used a blog post on my site, or might have used the Apple iPad page.  I'll try again next time I'm working on it, but if it works for you, perhaps I was using an older version or something.

**Comment by adamzolyak** [comment]
What ever happened to this?

**Comment by samuelclay** [comment]
That's a good question. I'm not sure if it's completed finished. @dejal, did we finish this or does it need more love?

**Comment by Dejal** [comment]
Been a while, but as I recall, it was finished but was in a separate branch, so may not have made it into the app.
